[tool.ruff]
select = [
  "E", "F", "W", # flake8
  "B",           # flake8-bugbear
  "I",           # isort
  "C4",          # flake8-comprehensions
  "ISC",         # flake8-implicit-str-concat
  "PGH",         # pygrep-hooks
  "PIE",         # flake8-pie
  "PL",          # pylint
  "PT",          # flake8-pytest-style
  "RUF",         # Ruff-specific
  "SIM",         # flake8-simplify
  "T20",         # flake8-print
  "UP",          # pyupgrade
  "YTT",         # flake8-2020
]
extend-ignore = [
  "PLR",     # Design related pylint codes
  "T201",    # print found
  "PT011",   # pytest.raises(Exception) is too broad
  "B017",    # pytest.raises(Exception) should be considered evil
  "ISC003",  # Explicitly concatenated string should be implicitly concatenated
  "B904",    # with `raise ... from err` or `raise ... from None`
]
src = ["bot"]
unfixable = [
  "T20",  # Removes print statements
]
exclude = []
